#!/bin/bash
#SBATCH --job-name=runBdDataTutPrec
#SBATCH --output foam3saveBd_startAt20000.log
#SBATCH --ntasks=288         # Change on setUp as well
#SBATCH --time=2:00:00
#SBATCH --account=car
#SBATCH --qos=high

source $HOME/.bash_profile
cores=$SLURM_NTASKS

echo "Working directory is" $SLURM_SUBMIT_DIR
echo "Job name is" $SLURM_JOB_NAME
echo "Starting OpenFOAM job at: " $(date)
echo "using" $cores "core(s)"

# ******************************************** USER INPUT ******************************************** #
OpenFOAM-6-gcc-dev              # OpenFOAM/SOWFA version. OpenFOAM-6-{icc,intel}-{central,dev}
startTime=20000                 # Start time (cp script for restarted runs)
solver=superDeliciousVanilla
# **************************************************************************************************** #

# **************************************** PERFORM SOME CHECKS *************************************** #
if [ ! -f foam2* ];                                                  then echo "Job killed (1)."; scancel $SLURM_JOBID; fi
if [ ! -f system/controlDict.$solver.aveBdData.startAt$startTime ];   then echo "Job killed (2)."; scancel $SLURM_JOBID; fi
if [ ! -f setUp ];                                                   then echo "Job killed (3)."; scancel $SLURM_JOBID; fi
if [ $(foamDictionary -entry "nCores" -value setUp) -ne $cores ];    then echo "Job killed (4)."; scancel $SLURM_JOBID; fi
# **************************************************************************************************** #

# ************************************ COPYING APPROPRIATE FILES ************************************* #
cp system/controlDict.$solver.saveBdData.startAt$startTime        system/controlDict
# **************************************************************************************************** #

# Run the solver
srun -n $cores --cpu_bind=cores $solver -parallel > log.3.$solver.saveBdData.startAt$startTime 2>&1

echo "Ending OpenFOAM job at: " $(date)

# **************************************************************************************************** #
