#!/bin/bash
#SBATCH --job-name=moveMeshBiglow51
#SBATCH --output foam1preprocess.log
#SBATCH --ntasks=792
#SBATCH --time=1:00:00
#SBATCH --account=car
#SBATCH --qos=high

source $HOME/.bash_profile
cores=$SLURM_NTASKS

cores=576

echo "Working directory is" $SLURM_SUBMIT_DIR
echo "Job name is" $SLURM_JOB_NAME
echo "Starting OpenFOAM job at: " $(date)
echo "using" $cores "core(s)"

# ******************************************** USER INPUT ******************************************** #
OpenFOAM-6-gcc-dev      # OpenFOAM/SOWFA version. OpenFOAM-6-{gcc,intel}-{central,dev}
startTime=0               # Start time
stabState=neutral         # neutral, stable, unstable
inflowDir=west            
meshSolver=moveDynamicMesh
terrainSTL=biglow_xm15001to16009_ym5005to15485_blendFlatNSEW_shifted.stl
# Make sure the terrain vertical bounding box is below zMin. Use `surfaceTransformPoints' to translate stl
# **************************************************************************************************** #

# ************************************ COPYING APPROPRIATE FILES ************************************* #
rm problemFaces
cd constant/triSurface  &&  ln -sf $terrainSTL    terrain.stl  &&  cd ../..
cp system/controlDict.$meshSolver.startAt$startTime    system/controlDict
cp setUp.$stabState                                    setUp
cp system/fvSolution.mesh                              system/fvSolution
cp system/fvSchemes.mesh                               system/fvSchemes
# **************************************************************************************************** #

# Make the mesh conform to the terrain boundary
srun -n $cores $meshSolver -noFunctionObjects -parallel > log.1.$meshSolver 2>&1

echo "Ending OpenFOAM job at: " $(date)

# **************************************************************************************************** #
